### ISSUE TITLE
环境搭建说明 (mvn clean install -DskipTests)

### ISSUE THREAD

**Issue by jeremyjia** [jeremyjia/Games#294]
**欢迎新朋友加入我们的漂泊者编程乐园团队，此文档用于帮助新加入的朋友搭建开发环境**

- [x] 整理成一篇推文，发到公众号上。
- [x] https://mp.weixin.qq.com/s/caDmK45ZbSJZet1ujr6o-A
- [x] https://mp.weixin.qq.com/s/Ubtx5d7r-1Rr_yVmA5OFWw

**Comment by jeremyjia** [comment]
1. 安装腾讯会议软件
2. 注册GitHub账户

**Comment by littleflute** [comment]
补充：
9. 完成上面的第2步后，Fork 本库。在自己的Fork 库上建立自己的主页。之后，做 pull request.

**Comment by waynexw** [comment]
请教问题，我配置Maven时，按照参考文献的指导，但是没能配置成功，输入mvn --version后没有出现版本号等信息，而是出现如下信息。
C:\>mvn -v
The JAVA_HOME environment variable is not defined correctly
This environment variable is needed to run this program
NB: JAVA_HOME should point to a JDK not a JRE

**Comment by jeremyjia** [comment]
Hi waynexw, 
如果你已经装好了Java JDK，可以参考下面的文章配置JAVA_HOME环境变量即可解决：
https://blog.csdn.net/qq_42017152/article/details/90732057

**Comment by waynexw** [comment]
> @waynexw
> 如果你已经装好了Java JDK，可以参考下面的文章配置JAVA_HOME环境变量即可解决：
> https://blog.csdn.net/qq_42017152/article/details/90732057

配置问题已经解决，多谢。

**Comment by waynexw** [comment]
请教问题：8. 代码下载成功后，进入到Games/Spring目录下运行以下命令（如果成功会看到BUILD SUCCESS），运行命令后，我看到如下提示，我觉得应该没能顺利完成配置过程。我觉得我虽然已经安装了Java JDK，但并没有在JDK上运行？

[INFO] Changes detected - recompiling the module!
[INFO] Compiling 25 source files to C:\Users\hasee\Games\Spring\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  07:33 min
[INFO] Finished at: 2021-04-24T16:38:12+10:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project pbz-demo: Compilation failure
[ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?

**Comment by waynexw** [comment]
> 补充：
> 9. 完成上面的第2步后，Fork 本库。在自己的Fork 库上建立自己的主页。之后，做 pull request.

请教黄老师，这句话我不是很清楚如何做？“在自己的Fork 库上建立自己的主页。之后，做 pull request.”

**Comment by jeremyjia** [comment]
> 请教问题：8. 代码下载成功后，进入到Games/Spring目录下运行以下命令（如果成功会看到BUILD SUCCESS），运行命令后，我看到如下提示，我觉得应该没能顺利完成配置过程。我觉得我虽然已经安装了Java JDK，但并没有在JDK上运行？
> 
> [INFO] Changes detected - recompiling the module!
> [INFO] Compiling 25 source files to C:\Users\hasee\Games\Spring\target\classes
> [INFO] -------------------------------------------------------------
> [ERROR] COMPILATION ERROR :
> [INFO] -------------------------------------------------------------
> [ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?
> [INFO] 1 error
> [INFO] -------------------------------------------------------------
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 07:33 min
> [INFO] Finished at: 2021-04-24T16:38:12+10:00
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project pbz-demo: Compilation failure
> [ERROR] No compiler is provided in this environment. Perhaps you are running on a JRE rather than a JDK?

@waynexw 试试在命令行里输入echo %JAVA_HOME%看看返回什么

**Comment by littleflute** [comment]
@waynexw 在Fork的库上，设置一下git-page功能，库的主页生效，象我们其他成员已经实现的那样，如下图，所有成员都有一个自己的主页。
![image](https://user-images.githubusercontent.com/17950965/115967849-c4249880-a4e9-11eb-9da8-5688997b1167.png)

**Comment by littleflute** [comment]
JDK1.8下载安装（Windows版） ref: https://blog.csdn.net/weixin_37601546/article/details/88623530
